apiVersion: template.openshift.io/v1
kind: Template
metadata:
name: backbase-pipeline
annotations:
openshift.io/display-name: Backbase Service pipeline
description: Backbase devops
iconClass: icon-java
tags: jenkins
objects:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: backbase-service-pipeline
    namespace: backbase-devops
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: {}
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: jenkins
      git:
        ref: master
        uri: https://github.com/hsaid4327/os-sample-java-web.git
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
      type: JenkinsPipeline
    successfulBuildsHistoryLimit: 5
    triggers: []
